# coding: utf-8

"""
    Gomematic OpenAPI

    API definition for Gomematic  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gomematic
from gomematic.api.profile_api import ProfileApi  # noqa: E501
from gomematic.rest import ApiException


class TestProfileApi(unittest.TestCase):
    """ProfileApi unit test stubs"""

    def setUp(self):
        self.api = gomematic.api.profile_api.ProfileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_show_profile(self):
        """Test case for show_profile

        Fetch profile details of the personal account  # noqa: E501
        """
        pass

    def test_token_profile(self):
        """Test case for token_profile

        Retrieve an unlimited auth token  # noqa: E501
        """
        pass

    def test_update_profile(self):
        """Test case for update_profile

        Update your own profile information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
