# coding: utf-8

"""
    Gomematic OpenAPI

    API definition for Gomematic  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gomematic
from gomematic.models.auth_token import AuthToken  # noqa: E501
from gomematic.rest import ApiException


class TestAuthToken(unittest.TestCase):
    """AuthToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthToken(self):
        """Test AuthToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gomematic.models.auth_token.AuthToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
