# coding: utf-8

"""
    Gomematic OpenAPI

    API definition for Gomematic  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gomematic
from gomematic.models.auth_verify import AuthVerify  # noqa: E501
from gomematic.rest import ApiException


class TestAuthVerify(unittest.TestCase):
    """AuthVerify unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthVerify(self):
        """Test AuthVerify"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gomematic.models.auth_verify.AuthVerify()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
